export const layoutRoomconstant = {
  financeRoom: {
    CabinSize: 50,
    SeatCount: 2,
  },
  confAndBoard: {
    CabinSize: 35,
    SeatCount: 2,
  },
  small: {
    CabinSize: 40,
    SeatCount: 2,
  },
  breakout: {
    CabinSize: 40,
  },
  commonRooms: {
    CabinSize: 5,
  },
  hrRoom: {
    CabinSize: 40,
    SeatCount: 2,
  },
};

export const initialAreaValues = {
  linear: 24,
  lType: 34,
  md: 120,
  manager: 80,
  small: 80,
  ups: 60,
  bms: 60,
  server: 40,
  reception: 80,
  lounge: 80,
  sales: 80,
  phoneBooth: 25,
  discussionRoom: 380,
  interviewRoom: 100,
  conferenceRoom: 250,
  boardRoom: 380,
  meetingRoom: 120,
  meetingRoomLarge: 150,
  hrRoom: 80,
  financeRoom: 100,
  breakoutRoom: 80,
  executiveWashroom: 60,
  videoRecordingRoom: 80,
  other: 1,
  washrooms: 100,
};

export const initialQuantities = {
  linear: 0,
  lType: 0,
  md: 0,
  manager: 0,
  small: 0,
  ups: 0,
  bms: 0,
  server: 0,
  reception: 0,
  lounge: 0,
  sales: 0,
  phoneBooth: 0,
  discussionRoom: 0,
  interviewRoom: 0,
  conferenceRoom: 0,
  boardRoom: 0,
  meetingRoom: 0,
  meetingRoomLarge: 0,
  hrRoom: 0,
  financeRoom: 0,
  breakoutRoom: 0,
  executiveWashroom: 0,
  videoRecordingRoom: 0,
  other: 0,
  washrooms: 0,
};
export const initialSeatCounts = {
  linear: 1,
  lType: 1,
  md: 3,
  manager: 3,
  small: 4,
  sales: 4,
  interviewRoom: 3,
  conferenceRoom: 12,
  boardRoom: 18,
  meetingRoom: 6,
  meetingRoomLarge: 8,
  hrRoom: 4,
  financeRoom: 4,
  ups: 1,
  bms: 1,
  server: 1,
  reception: 1,
  lounge: 1,
  phoneBooth: 1,
  breakoutRoom: 1,
  executiveWashroom: 1,
  videoRecordingRoom: 1,
  other: 1,
  washrooms: 1,
};

export const fullNames = {
  linear: "Linear Workspace",
  lType: "L-Type Workspace",
  md: "MD Cabin",
  manager: "Manager Cabin",
  small: "Small Cabin",
  ups: "UPS Room",
  bms: "BMS Room",
  server: "Server Room",
  reception: "Reception",
  lounge: "Lounge",
  fitness: "Fitness Zone",
  sales: "Sales Team",
  phoneBooth: "Phone Booth",
  discussionRoom: "Discussion Room",
  interviewRoom: "Interview Room",
  conferenceRoom: "Conference Room",
  boardRoom: "Board Room",
  meetingRoom: "Meeting Room",
  meetingRoomLarge: "Meeting Room (L)",
  hrRoom: "HR Room",
  financeRoom: "Finance Room",
  executiveWashroom: "Executive Washroom",
  breakoutRoom: "Breakout Room",
  videoRecordingRoom: "Video Recording Room",
  other: "Other",
  washrooms: "Wash rooms",
};

export const workspaceImages = {
  "Linear Workspace": "/images/workstation-wp/linear.webp",
  "L-Type Workspace": "/images/workstation-wp/lType.webp",
  "MD Cabin": "/images/workstation-wp/md.webp",
  "Manager Cabin": "/images/workstation-wp/manager.webp",
  "Small Cabin": "/images/workstation-wp/smallCabin.webp",
  "UPS Room": "/images/workstation-wp/ups.webp",
  "BMS Room": "/images/workstation-wp/bms.webp",
  "Server Room": "/images/workstation-wp/serverRoom.webp",
  Reception: "/images/workstation-wp/reception.webp",
  Lounge: "/images/workstation-wp/lounge.webp",
  "Video Recording Room": "/images/workstation-wp/videoRoom.webp",
  "Sales Team": "/images/workstation-wp/salesRoom.webp",
  "Phone Booth": "/images/workstation-wp/phoneBooth.webp",
  "Discussion Room": "/images/workstation-wp/discussionRoom.png",
  "Interview Room": "/images/workstation-wp/interview.webp",
  "Conference Room": "/images/workstation-wp/conferenceRoom.webp",
  "Board Room": "/images/workstation-wp/boardRoom.webp",
  "Meeting Room": "/images/workstation-wp/meetingRoom.webp",
  "Meeting Room (L)": "/images/workstation-wp/meetingRoomLarge.webp",
  "HR Room": "/images/workstation-wp/hrRoom.webp",
  "Finance Room": "/images/workstation-wp/financeRoom.webp",
  "Executive Washroom": "/images/workstation-wp/executiveWashroom.webp",
  "Breakout Room": "/images/workstation-wp/breakout.webp",
  Other: "/images/workstation-wp/others.webp",
  "Wash rooms": "/images/workstation-wp/washroom.webp",
};
