export const baseImageUrl =
  "https://bwxzfwsoxwtzhjbzbdzs.supabase.co/storage/v1/object/public/addon/";

export const blogImageUrl =
  "https://bwxzfwsoxwtzhjbzbdzs.supabase.co/storage/v1/object/public/blog-images";
export const resumeUrl =
  "https://bwxzfwsoxwtzhjbzbdzs.supabase.co/storage/v1/object/public/jobData";

export const additionalDetailsConfig = [
  {
    category: "furniture",
    subcategory: "table",
    fields: [
      {
        label: "Use-case",
        name: "useCase",
        type: "text",
        placeholder: "Dining  / Coffee Table",
      },
      {
        label: "Finish Type",
        name: "finishType",
        type: "text",
        placeholder: "Matte / Glossy / Natural Wood",
      },
      {
        label: "Frame Joint Type",
        name: "frameJointType",
        type: "text",
        placeholder: "Mortise & Tenon / Screwed / Welded",
      },
      {
        label: "Maximum Weight Recommendation",
        name: "maximumWeightRecommendation",
        type: "text",
        placeholder: "Up to 120 kg",
      },
      {
        label: "Base Type",
        name: "baseType",
        type: "text",
        placeholder: "Pedestal / Four-Leg / Trestle",
      },
      {
        label: "Tabletop Thickness",
        name: "tabletopThickness",
        type: "text",
        placeholder: "18 mm / 25 mm / 30 mm",
      },
    ],
  },
  {
    category: "furniture",
    subcategory: "chair",
    fields: [
      {
        label: "Use-case",
        name: "useCase",
        type: "text",
        placeholder: "Office / Dining / Lounge",
      },
      {
        label: "Back Style",
        name: "backStyle",
        type: "text",
        placeholder: "High-back / Mid-back / Low-back",
      },
      {
        label: "Seat Material Type",
        name: "seatMaterialType",
        type: "text",
        placeholder: "Fabric / Leather / Mesh",
      },
      {
        label: "Fill Material",
        name: "fillMaterial",
        type: "text",
        placeholder: "Foam / Fiber / Cushion Padding",
      },
      {
        label: "Reclining Position Count",
        name: "recliningPositionCount",
        type: "text",
        placeholder: "1–4 Adjustable Positions",
      },
    ],
  },
  {
    category: "furniture",
    subcategory: "storage",
    fields: [
      {
        label: "Use-case",
        name: "useCase",
        type: "text",
        placeholder: "Office Storage",
      },
      {
        label: "Door Style",
        name: "doorStyle",
        type: "text",
        placeholder: "Hinged Door",
      },
      {
        label: "Mounting Type",
        name: "mountingType",
        type: "text",
        placeholder: "Wall-mounted",
      },
      {
        label: "Number of Racks",
        name: "numberOfRacks",
        type: "text",
        placeholder: "4 Racks",
      },
      {
        label: "Base Type",
        name: "baseType",
        type: "text",
        placeholder: "Solid Base",
      },
      {
        label: "Lock Type",
        name: "lockType",
        type: "text",
        placeholder: "Key Lock",
      },
    ],
  },
  {
    category: "furniture",
    subcategory: "sofas",
    fields: [
      {
        label: "Use-case",
        name: "useCase",
        type: "text",
        placeholder: "Living Room Sofa",
      },
      {
        label: "Seating Capacity",
        name: "seatingCapacity",
        type: "text",
        placeholder: "3 Seater",
      },
      {
        label: "Seat Depth",
        name: "seatDepth",
        type: "text",
        placeholder: "22 inches",
      },
      {
        label: "Seat Height",
        name: "seatHeight",
        type: "text",
        placeholder: "18 inches",
      },
      {
        label: "Seat Back Fill Material",
        name: "seatBackFillMaterial",
        type: "text",
        placeholder: "Foam",
      },
    ],
  },
  {
    category: "furniture",
    subcategory: "side table",
    fields: [
      {
        label: "Use-case",
        name: "useCase",
        type: "text",
        placeholder: "Bedside Use",
      },
      {
        label: "Finish Type",
        name: "finishType",
        type: "text",
        placeholder: "Matte Finish",
      },
      {
        label: "Frame Joint Type",
        name: "frameJointType",
        type: "text",
        placeholder: "Screwed Joint",
      },
      {
        label: "Maximum Weight Recommendation",
        name: "maximumWeightRecommendation",
        type: "text",
        placeholder: "20 kg",
      },
      {
        label: "Base Type",
        name: "baseType",
        type: "text",
        placeholder: "Four-Leg Base",
      },
      {
        label: "Tabletop Thickness",
        name: "tabletopThickness",
        type: "text",
        placeholder: "18 mm",
      },
    ],
  },
  {
    category: "furniture",
    subcategory: "tv console",
    fields: [
      {
        label: "Use-case",
        name: "useCase",
        type: "text",
        placeholder: "Living Room TV Unit",
      },
      {
        label: "Door Style",
        name: "doorStyle",
        type: "text",
        placeholder: "Sliding Door",
      },
      {
        label: "Mounting Type",
        name: "mountingType",
        type: "text",
        placeholder: "Wall-mounted",
      },
      {
        label: "Number of Compartments",
        name: "numberOfCompartments",
        type: "text",
        placeholder: "3 Compartments",
      },
      {
        label: "Base Type",
        name: "baseType",
        type: "text",
        placeholder: "Floating Base",
      },
    ],
  },
  {
    category: "furniture",
    subcategory: "coffee table",
    fields: [
      {
        label: "Use-case",
        name: "useCase",
        type: "text",
        placeholder: "Living Room Center Table",
      },
      {
        label: "Finish Type",
        name: "finishType",
        type: "text",
        placeholder: "Natural Wood Finish",
      },
      {
        label: "Frame Joint Type",
        name: "frameJointType",
        type: "text",
        placeholder: "Mortise Joint",
      },
      {
        label: "Maximum Weight Recommendation",
        name: "maximumWeightRecommendation",
        type: "text",
        placeholder: "40 kg",
      },
      {
        label: "Base Type",
        name: "baseType",
        type: "text",
        placeholder: "Four-Leg Base",
      },
      {
        label: "Tabletop Thickness",
        name: "tabletopThickness",
        type: "text",
        placeholder: "20 mm",
      },
    ],
  },
  {
    category: "lighting",
    subcategory: "ambient",
    fields: [
      {
        label: "Use-case",
        name: "useCase",
        type: "text",
        placeholder: "Indoor Ambient Lighting",
      },
      {
        label: "Lighting Type",
        name: "lightingType",
        type: "text",
        placeholder: "Soft Diffused Light",
      },
      {
        label: "Installation Type",
        name: "installationType",
        type: "text",
        placeholder: "Ceiling-mounted",
      },
      {
        label: "Voltage / Wattage",
        name: "voltageWattage",
        type: "text",
        placeholder: "12W",
      },
      {
        label: "Switch Installation Type",
        name: "switchInstallationType",
        type: "text",
        placeholder: "Wall Switch",
      },
      {
        label: "Light Source Type",
        name: "lightSourceType",
        type: "text",
        placeholder: "LED",
      },
      {
        label: "Light Colour",
        name: "lightColour",
        type: "text",
        placeholder: "Warm White",
      },
      {
        label: "Color Temperature",
        name: "colorTemperature",
        type: "text",
        placeholder: "3000K",
      },
    ],
  },
  {
    category: "lighting",
    subcategory: "task",
    fields: [
      {
        label: "Use-case",
        name: "useCase",
        type: "text",
        placeholder: "Indoor Ambient Lighting",
      },
      {
        label: "Lighting Type",
        name: "lightingType",
        type: "text",
        placeholder: "Soft Diffused Light",
      },
      {
        label: "Installation Type",
        name: "installationType",
        type: "text",
        placeholder: "Ceiling-mounted",
      },
      {
        label: "Voltage / Wattage",
        name: "voltageWattage",
        type: "text",
        placeholder: "12W",
      },
      {
        label: "Switch Installation Type",
        name: "switchInstallationType",
        type: "text",
        placeholder: "Wall Switch",
      },
      {
        label: "Light Source Type",
        name: "lightSourceType",
        type: "text",
        placeholder: "LED",
      },
      {
        label: "Light Colour",
        name: "lightColour",
        type: "text",
        placeholder: "Warm White",
      },
      {
        label: "Color Temperature",
        name: "colorTemperature",
        type: "text",
        placeholder: "3000K",
      },
    ],
  },
  {
    category: "lighting",
    subcategory: "Accent",
    fields: [
      {
        label: "Use-case",
        name: "useCase",
        type: "text",
        placeholder: "Indoor Ambient Lighting",
      },
      {
        label: "Lighting Type",
        name: "lightingType",
        type: "text",
        placeholder: "Soft Diffused Light",
      },
      {
        label: "Installation Type",
        name: "installationType",
        type: "text",
        placeholder: "Ceiling-mounted",
      },
      {
        label: "Voltage / Wattage",
        name: "voltageWattage",
        type: "text",
        placeholder: "12W",
      },
      {
        label: "Switch Installation Type",
        name: "switchInstallationType",
        type: "text",
        placeholder: "Wall Switch",
      },
      {
        label: "Light Source Type",
        name: "lightSourceType",
        type: "text",
        placeholder: "LED",
      },
      {
        label: "Light Colour",
        name: "lightColour",
        type: "text",
        placeholder: "Warm White",
      },
      {
        label: "Color Temperature",
        name: "colorTemperature",
        type: "text",
        placeholder: "3000K",
      },
    ],
  },
  {
    category: "hvac",
    subcategory: "centralized Ac",
    fields: [
      {
        label: "Use-case",
        name: "useCase",
        type: "text",
        placeholder: "Commercial HVAC",
      },
      {
        label: "Energy Efficiency",
        name: "energyEfficiency",
        type: "text",
        placeholder: "5 Star",
      },
      {
        label: "Installation Type",
        name: "installationType",
        type: "text",
        placeholder: "Wall-mounted",
      },
      {
        label: "Cooling Capacity (Tons / BTU)",
        name: "coolingCapacity",
        type: "text",
        placeholder: "1.5 Ton",
      },
      {
        label: "Airflow & Filtration",
        name: "airflowFiltration",
        type: "text",
        placeholder: "HEPA Filter",
      },
      {
        label: "Form Factor",
        name: "formFactor",
        type: "text",
        placeholder: "Split AC",
      },
      {
        label: "Voltage / Wattage",
        name: "voltageWattage",
        type: "text",
        placeholder: "230V / 1500W",
      },
      {
        label: "Model",
        name: "model",
        type: "text",
        placeholder: "XR-1200",
      },
      {
        label: "Capacity",
        name: "capacity",
        type: "text",
        placeholder: "350 CFM",
      },
      {
        label: "Annual Energy Consumption",
        name: "annualEnergyConsumption",
        type: "text",
        placeholder: "1200 kWh",
      },
      {
        label: "Type",
        name: "type",
        type: "text",
        placeholder: "Inverter",
      },
    ],
  },
  {
    category: "hvac",
    subcategory: "combination",
    fields: [
      {
        label: "Use-case",
        name: "useCase",
        type: "text",
        placeholder: "Commercial HVAC",
      },
      {
        label: "Energy Efficiency",
        name: "energyEfficiency",
        type: "text",
        placeholder: "5 Star",
      },
      {
        label: "Installation Type",
        name: "installationType",
        type: "text",
        placeholder: "Wall-mounted",
      },
      {
        label: "Cooling Capacity (Tons / BTU)",
        name: "coolingCapacity",
        type: "text",
        placeholder: "1.5 Ton",
      },
      {
        label: "Airflow & Filtration",
        name: "airflowFiltration",
        type: "text",
        placeholder: "HEPA Filter",
      },
      {
        label: "Form Factor",
        name: "formFactor",
        type: "text",
        placeholder: "Split AC",
      },
      {
        label: "Voltage / Wattage",
        name: "voltageWattage",
        type: "text",
        placeholder: "230V / 1500W",
      },
      {
        label: "Model",
        name: "model",
        type: "text",
        placeholder: "XR-1200",
      },
      {
        label: "Capacity",
        name: "capacity",
        type: "text",
        placeholder: "350 CFM",
      },
      {
        label: "Annual Energy Consumption",
        name: "annualEnergyConsumption",
        type: "text",
        placeholder: "1200 kWh",
      },
      {
        label: "Type",
        name: "type",
        type: "text",
        placeholder: "Inverter",
      },
    ],
  },
  {
    category: "hvac",
    subcategory: "vrv",
    fields: [
      {
        label: "Use-case",
        name: "useCase",
        type: "text",
        placeholder: "Commercial HVAC",
      },
      {
        label: "Energy Efficiency",
        name: "energyEfficiency",
        type: "text",
        placeholder: "5 Star",
      },
      {
        label: "Installation Type",
        name: "installationType",
        type: "text",
        placeholder: "Wall-mounted",
      },
      {
        label: "Cooling Capacity (Tons / BTU)",
        name: "coolingCapacity",
        type: "text",
        placeholder: "1.5 Ton",
      },
      {
        label: "Airflow & Filtration",
        name: "airflowFiltration",
        type: "text",
        placeholder: "HEPA Filter",
      },
      {
        label: "Form Factor",
        name: "formFactor",
        type: "text",
        placeholder: "Split AC",
      },
      {
        label: "Voltage / Wattage",
        name: "voltageWattage",
        type: "text",
        placeholder: "230V / 1500W",
      },
      {
        label: "Model",
        name: "model",
        type: "text",
        placeholder: "XR-1200",
      },
      {
        label: "Capacity",
        name: "capacity",
        type: "text",
        placeholder: "350 CFM",
      },
      {
        label: "Annual Energy Consumption",
        name: "annualEnergyConsumption",
        type: "text",
        placeholder: "1200 kWh",
      },
      {
        label: "Type",
        name: "type",
        type: "text",
        placeholder: "Inverter",
      },
    ],
  },
  {
    category: "hvac",
    subcategory: "Ac",
    fields: [
      {
        label: "Use-case",
        name: "useCase",
        type: "text",
        placeholder: "Commercial HVAC",
      },
      {
        label: "Energy Efficiency",
        name: "energyEfficiency",
        type: "text",
        placeholder: "5 Star",
      },
      {
        label: "Installation Type",
        name: "installationType",
        type: "text",
        placeholder: "Wall-mounted",
      },
      {
        label: "Cooling Capacity (Tons / BTU)",
        name: "coolingCapacity",
        type: "text",
        placeholder: "1.5 Ton",
      },
      {
        label: "Airflow & Filtration",
        name: "airflowFiltration",
        type: "text",
        placeholder: "HEPA Filter",
      },
      {
        label: "Form Factor",
        name: "formFactor",
        type: "text",
        placeholder: "Split AC",
      },
      {
        label: "Voltage / Wattage",
        name: "voltageWattage",
        type: "text",
        placeholder: "230V / 1500W",
      },
      {
        label: "Model",
        name: "model",
        type: "text",
        placeholder: "XR-1200",
      },
      {
        label: "Capacity",
        name: "capacity",
        type: "text",
        placeholder: "350 CFM",
      },
      {
        label: "Annual Energy Consumption",
        name: "annualEnergyConsumption",
        type: "text",
        placeholder: "1200 kWh",
      },
      {
        label: "Type",
        name: "type",
        type: "text",
        placeholder: "Inverter",
      },
    ],
  },
  {
    category: "flooring",
    subcategory: "carpet",
    fields: [
      {
        label: "Product Care Instructions",
        name: "productCareInstructions",
        type: "text",
        placeholder: "Vacuum regularly",
      },
      {
        label: "Weave Type",
        name: "weaveType",
        type: "text",
        placeholder: "Machine-woven",
      },
      {
        label: "Back Material Type",
        name: "backMaterialType",
        type: "text",
        placeholder: "Latex Backing",
      },
      {
        label: "Item Thickness",
        name: "itemThickness",
        type: "text",
        placeholder: "10 mm",
      },
      {
        label: "Rug Form Type",
        name: "rugFormType",
        type: "text",
        placeholder: "Area Rug",
      },
      {
        label: "Acoustic Performance",
        name: "acousticPerformance",
        type: "text",
        placeholder: "Noise Reduction",
      },
      {
        label: "Installation Method",
        name: "installationMethod",
        type: "text",
        placeholder: "Loose Lay",
      },
      {
        label: "Finish",
        name: "finish",
        type: "text",
        placeholder: "Textured Finish",
      },
    ],
  },
  {
    category: "flooring",
    subcategory: "tile",
    fields: [
      {
        label: "Product Care Instructions",
        name: "productCareInstructions",
        type: "text",
        placeholder: "Clean with mild detergent",
      },
      {
        label: "Finish Type",
        name: "finishType",
        type: "text",
        placeholder: "Glossy Finish",
      },
      {
        label: "Thickness",
        name: "thickness",
        type: "text",
        placeholder: "8 mm",
      },
      {
        label: "Shape",
        name: "shape",
        type: "text",
        placeholder: "Square",
      },
      {
        label: "Pattern / Design",
        name: "patternDesign",
        type: "text",
        placeholder: "Marble Pattern",
      },
      {
        label: "Finish",
        name: "finish",
        type: "text",
        placeholder: "Smooth Finish",
      },
      {
        label: "Acoustic Performance",
        name: "acousticPerformance",
        type: "text",
        placeholder: "Low Noise Transmission",
      },
      {
        label: "Installation Method",
        name: "installationMethod",
        type: "text",
        placeholder: "Cement Grout",
      },
    ],
  },
  {
    category: "flooring",
    subcategory: "vinyl",
    fields: [
      {
        label: "Product Care Instructions",
        name: "productCareInstructions",
        type: "text",
        placeholder: "Sweep and mop regularly",
      },
      {
        label: "Pattern / Design",
        name: "patternDesign",
        type: "text",
        placeholder: "Wood Grain",
      },
      {
        label: "Finish",
        name: "finish",
        type: "text",
        placeholder: "Matte Finish",
      },
      {
        label: "Acoustic Performance",
        name: "acousticPerformance",
        type: "text",
        placeholder: "Sound Absorption",
      },
      {
        label: "Installation Method",
        name: "installationMethod",
        type: "text",
        placeholder: "Click Lock",
      },
      {
        label: "Back Material Type",
        name: "backMaterialType",
        type: "text",
        placeholder: "Foam Backing",
      },
    ],
  },
  {
    category: "flooring",
    subcategory: "epoxy",
    fields: [
      {
        label: "Product Care Instructions",
        name: "productCareInstructions",
        type: "text",
        placeholder: "Wipe with mild cleaner",
      },
      {
        label: "Water Resistance Level",
        name: "waterResistanceLevel",
        type: "text",
        placeholder: "Highly Water-Resistant",
      },
      {
        label: "Surface Recommendation",
        name: "surfaceRecommendation",
        type: "text",
        placeholder: "Concrete Floors",
      },
    ],
  },
  {
    category: "civil / plumbing",
    subcategory: "tile",
    fields: [
      {
        label: "Product Care Instructions",
        name: "productCareInstructions",
        type: "text",
        placeholder: "Clean with mild detergent",
      },
      {
        label: "Finish Type",
        name: "finishType",
        type: "text",
        placeholder: "Matte Finish",
      },
      {
        label: "Thickness",
        name: "thickness",
        type: "text",
        placeholder: "10 mm",
      },
      {
        label: "Shape",
        name: "shape",
        type: "text",
        placeholder: "Rectangular",
      },
      {
        label: "Pattern / Design",
        name: "patternDesign",
        type: "text",
        placeholder: "Stone Pattern",
      },
      {
        label: "Compliance",
        name: "compliance",
        type: "text",
        placeholder: "ISI Certified",
      },
    ],
  },
  {
    category: "civil / plumbing",
    subcategory: "basin",
    fields: [
      {
        label: "Product Care Instructions",
        name: "productCareInstructions",
        type: "text",
        placeholder: "Clean with mild soap",
      },
      {
        label: "Installation Type",
        name: "installationType",
        type: "text",
        placeholder: "Wall-mounted",
      },
      {
        label: "Finish Type",
        name: "finishType",
        type: "text",
        placeholder: "Ceramic Gloss",
      },
      {
        label: "Drain Type",
        name: "drainType",
        type: "text",
        placeholder: "Standard Drain",
      },
      {
        label: "Shape",
        name: "shape",
        type: "text",
        placeholder: "Oval",
      },
      {
        label: "Compliance",
        name: "compliance",
        type: "text",
        placeholder: "ISI Certified",
      },
    ],
  },
  {
    category: "civil / plumbing",
    subcategory: "pods",
    fields: [
      {
        label: "Product Care Instructions",
        name: "productCareInstructions",
        type: "text",
        placeholder: "Wipe with mild disinfectant",
      },
      {
        label: "Installation Type",
        name: "installationType",
        type: "text",
        placeholder: "Pre-fabricated Installation",
      },
      {
        label: "Seat Material Type",
        name: "seatMaterialType",
        type: "text",
        placeholder: "High-Density Plastic",
      },
      {
        label: "Shape",
        name: "shape",
        type: "text",
        placeholder: "Compact Rectangular",
      },
      {
        label: "Compliance",
        name: "compliance",
        type: "text",
        placeholder: "Building Code Compliant",
      },
    ],
  },
  {
    category: "partitions / ceilings",
    subcategory: "glass partition",
    fields: [
      {
        label: "Product Care Instructions",
        name: "productCareInstructions",
        type: "text",
        placeholder: "Clean with glass cleaner",
      },
      {
        label: "Water Resistance Level",
        name: "waterResistanceLevel",
        type: "text",
        placeholder: "Water-Resistant",
      },
      {
        label: "Installation Type",
        name: "installationType",
        type: "text",
        placeholder: "Framed Installation",
      },
      {
        label: "Sound Rating",
        name: "soundRating",
        type: "text",
        placeholder: "30 dB",
      },
      {
        label: "Finish",
        name: "finish",
        type: "text",
        placeholder: "Frosted Finish",
      },
      {
        label: "Installation",
        name: "installation",
        type: "text",
        placeholder: "Professional Installation",
      },
    ],
  },
  {
    category: "partitions / ceilings",
    subcategory: "gypsum partition",
    fields: [
      {
        label: "Thickness",
        name: "thickness",
        type: "text",
        placeholder: "12 mm",
      },
      {
        label: "Sound Rating",
        name: "soundRating",
        type: "text",
        placeholder: "45 dB",
      },
      {
        label: "Finish",
        name: "finish",
        type: "text",
        placeholder: "Smooth Paint Finish",
      },
      {
        label: "Installation",
        name: "installation",
        type: "text",
        placeholder: "Metal Stud Framing",
      },
    ],
  },
  {
    category: "paint",
    subcategory: "walls",
    fields: [
      {
        label: "Product Care Instructions",
        name: "productCareInstructions",
        type: "text",
        placeholder: "Wipe with damp cloth",
      },
      {
        label: "Paint Type",
        name: "paintType",
        type: "text",
        placeholder: "Acrylic Emulsion",
      },
      {
        label: "Water Resistance Level",
        name: "waterResistanceLevel",
        type: "text",
        placeholder: "Highly Water-Resistant",
      },
      {
        label: "Maintenance",
        name: "maintenance",
        type: "text",
        placeholder: "Low Maintenance",
      },
    ],
  },
  {
    category: "paint",
    subcategory: "ceilings",
    fields: [
      {
        label: "Product Care Instructions",
        name: "productCareInstructions",
        type: "text",
        placeholder: "Wipe with damp cloth",
      },
      {
        label: "Paint Type",
        name: "paintType",
        type: "text",
        placeholder: "Acrylic Emulsion",
      },
      {
        label: "Water Resistance Level",
        name: "waterResistanceLevel",
        type: "text",
        placeholder: "Highly Water-Resistant",
      },
      {
        label: "Maintenance",
        name: "maintenance",
        type: "text",
        placeholder: "Low Maintenance",
      },
    ],
  },
  {
    category: "smart solutions",
    subcategory: "cctv",
    fields: [
      {
        label: "Product Care Instructions",
        name: "productCareInstructions",
        type: "text",
        placeholder: "Clean lens regularly",
      },
      {
        label: "Wireless Communication Technology",
        name: "wirelessCommunicationTechnology",
        type: "text",
        placeholder: "Wi-Fi",
      },
      {
        label: "Zoom Type",
        name: "zoomType",
        type: "text",
        placeholder: "Digital Zoom",
      },
      {
        label: "Video Capture Format",
        name: "videoCaptureFormat",
        type: "text",
        placeholder: "1080p HD",
      },
      {
        label: "Resolution",
        name: "resolution",
        type: "text",
        placeholder: "1920 x 1080",
      },
      {
        label: "Flash Memory Type",
        name: "flashMemoryType",
        type: "text",
        placeholder: "MicroSD",
      },
      {
        label: "Connectivity",
        name: "connectivity",
        type: "text",
        placeholder: "Wi-Fi / Ethernet",
      },
      {
        label: "Compatibility",
        name: "compatibility",
        type: "text",
        placeholder: "Mobile App",
      },
      {
        label: "Security & Monitoring",
        name: "securityMonitoring",
        type: "text",
        placeholder: "Motion Detection Alerts",
      },
    ],
  },
  {
    category: "smart solutions",
    subcategory: "biometric",
    fields: [
      {
        label: "Product Care Instructions",
        name: "productCareInstructions",
        type: "text",
        placeholder: "Clean sensor gently",
      },
      {
        label: "Batteries Required",
        name: "batteriesRequired",
        type: "text",
        placeholder: "Yes",
      },
      {
        label: "Control Method",
        name: "controlMethod",
        type: "text",
        placeholder: "App / Keypad",
      },
      {
        label: "Connectivity",
        name: "connectivity",
        type: "text",
        placeholder: "Wi-Fi / Bluetooth",
      },
      {
        label: "Compatibility",
        name: "compatibility",
        type: "text",
        placeholder: "iOS & Android",
      },
    ],
  },
  {
    category: "smart solutions",
    subcategory: "locker",
    fields: [
      {
        label: "Product Care Instructions",
        name: "productCareInstructions",
        type: "text",
        placeholder: "Enter product care instructions",
      },
      {
        label: "Capacity",
        name: "capacity",
        type: "text",
        placeholder: "Enter storage capacity",
      },
      {
        label: "Mounting Type",
        name: "mountingType",
        type: "text",
        placeholder: "Enter mounting type (e.g., Wall Mounted, Floor Standing)",
      },
    ],
  },
  {
    category: "lux",
    subcategory: "deco",
    fields: [
      {
        label: "Product Care Instructions",
        name: "productCareInstructions",
        type: "text",
        placeholder: "Enter product care instructions",
      },
      {
        label: "Design Approach",
        name: "designApproach",
        type: "text",
        placeholder: "Describe the design approach",
      },
      {
        label: "Brand Story",
        name: "brandStory",
        type: "text",
        placeholder: "Enter brand story (Italian, etc.)",
      },
      {
        label: "Exclusive Features",
        name: "exclusiveFeatures",
        type: "text",
        placeholder: "Enter exclusive features",
      },
    ],
  },
  {
    category: "lux",
    subcategory: "lights",
    fields: [
      {
        label: "Product Care Instructions",
        name: "productCareInstructions",
        type: "text",
        placeholder: "Enter product care instructions",
      },
      {
        label: "Design Approach",
        name: "designApproach",
        type: "text",
        placeholder: "Describe the design approach",
      },
      {
        label: "Brand Story",
        name: "brandStory",
        type: "text",
        placeholder: "Enter brand story (Italian, etc.)",
      },
      {
        label: "Exclusive Features",
        name: "exclusiveFeatures",
        type: "text",
        placeholder: "Enter exclusive features",
      },
    ],
  },
];

export const productInfoFields = [
  {
    label: "Product Color",
    name: "ProductColor",
    placeholder: "Eg: Black Grey (HB)",
    type: "text",
  },
  {
    label: "Material",
    name: "Material",
    placeholder: "eg: High Quality PP Seat & Beech Wood Legs",
    type: "text",
  },
  {
    label: "Body Material",
    name: "BodyMaterial",
    placeholder: "",
    type: "text",
  },
  {
    label: "Brand",
    name: "Brand",
    placeholder: "brand name",
    type: "text",
  },
  {
    label: "Product care instructions",
    name: "ProductCareInstructions",
    placeholder: "eg: Wipe Clean",
    type: "text",
  },
  {
    label: "Special Feature",
    name: "SpecialFeature",
    placeholder: "eg: Ergonomic",
    type: "text",
  },
  {
    label: "product Weight",
    name: "ProductWeight",
    placeholder: "120",
    type: "text",
  },
];
